import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='bg-cyan-300'>Header</header>
        {children}
        <Link href='/csr'>CSR</Link>
        <footer className='bg-slate-500'>Footer</footer>
      </body>
    </html>
  );
}
